server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exChangeApp
    driverClassName: org.postgresql.Driver
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/changelog-master.yml
    enabled: true
    drop-first: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
